// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-0IwpVSSbCyuZwQXlEHr89yGn4hNb278',
    appId: '1:40256357384:web:b3b9b5022fbb4adf78bdbd',
    messagingSenderId: '40256357384',
    projectId: 'my-todo-list-4bcf5',
    authDomain: 'my-todo-list-4bcf5.firebaseapp.com',
    storageBucket: 'my-todo-list-4bcf5.appspot.com',
    measurementId: 'G-X8DK80YS91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQPdqTzhvVGEoT12ROU6t3VD31UWfExm4',
    appId: '1:40256357384:android:2e36b92ee99ce5cc78bdbd',
    messagingSenderId: '40256357384',
    projectId: 'my-todo-list-4bcf5',
    storageBucket: 'my-todo-list-4bcf5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-0IwpVSSbCyuZwQXlEHr89yGn4hNb278',
    appId: '1:40256357384:web:7fbb9a676b577ad778bdbd',
    messagingSenderId: '40256357384',
    projectId: 'my-todo-list-4bcf5',
    authDomain: 'my-todo-list-4bcf5.firebaseapp.com',
    storageBucket: 'my-todo-list-4bcf5.appspot.com',
    measurementId: 'G-Z3VL767F31',
  );
}
